name: CI-macos

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-11

    steps:         
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
                                        
      - name: Esy setup
        run: |
          brew install libtool gettext
          npm install -g esy@latest
          npm install -g node-gyp
          node-gyp install 14.15.4
          node install-node-deps.js
          esy install
          esy bootstrap
          esy build --verbosity=debug
          esy run -f --checkhealth
          echo "first checkhealth"
          esy '@release' install
          esy '@release' run -f --checkhealth
          echo "second checkhealth"
          esy '@release' run --help
          echo "third run"
          esy '@release' create
          ls -al
          ./_release/Onivim2.app/Contents/MacOS/Oni2 -f --checkhealth
          echo "last checkhealth"
          ./scripts/osx/package.sh
          tar -cvf AppDir.tar _publish
          
      - uses: actions/upload-artifact@v3
        with: 
          name: AppDirMac
          path: AppDir.tar
