name: CI

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Delete
        uses: jimschubert/delete-artifacts-action@v1
        with:
          log_level: 'debug'
          min_bytes: '0'
          
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Get latest tag
        id: getTag
        run: |
          GIT_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo ::set-output name=gitTag::${GIT_TAG}

      - name: Esy setup
        run: |
          rm -rf ~/.esy
          docker build --network=host -t centos scripts/docker/centos
          docker container run --rm \
              --name centos \
              --network=host \
              --volume `pwd`:/oni2 \
              --volume ~/.esy:/esy/store \
              --cap-add SYS_ADMIN \
              --device /dev/fuse \
              --security-opt apparmor:unconfined \
              centos \
              /bin/bash -c 'cd oni2 && ./scripts/docker-build.sh'
          tar -cvf AppDir.tar _release/Onivim2.AppDir
          tar -cvf AppCache.tar ~/.esy
          rm -rf ~/.esy
              
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: _release/Onivim2.AppDir
            
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ steps.getTag.outputs.gitTag }}
          prerelease: false
          files: |
            AppDir.tar
            AppCache.tar
