name: CI-nightly

on:  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Delete
        uses: jimschubert/delete-artifacts-action@v1
        with:
          log_level: 'debug'
          min_bytes: '0'
          
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Esy setup
        run: |
          id
          docker build --network=host -t ubuntu scripts/docker/ubuntu
          sudo -u runner docker container run --rm \
              --user "$(id -u):$(id -g)" \
              --name ubuntu \
              --network=host \
              --volume `pwd`:/oni2 \
              --volume ~/.esy:/esy/store \
              --cap-add SYS_ADMIN \
              --device /dev/fuse \
              --security-opt apparmor:unconfined \
              ubuntu \
              /bin/bash -c 'cd oni2 && id && ls -n / | grep oni2'
          exit 1
          rm -rf ~/.esy
          rm -rf /esy/store
          docker build --network=host -t ubuntu scripts/docker/ubuntu
          docker container run --rm \
              --name ubuntu \
              --network=host \
              --volume `pwd`:/oni2 \
              --volume ~/.esy:/esy/store \
              --cap-add SYS_ADMIN \
              --device /dev/fuse \
              --security-opt apparmor:unconfined \
              ubuntu \
              /bin/bash -c 'cd oni2 && ./scripts/docker-ubuntu-build.sh "./scripts/patches/package.patch"'
          tar -cvf AppDir.tar _release/Onivim2.AppDir
          mkdir AppCache
          cp -r $(find ~/.esy -type d -path '*i/*camomile-opam*/share/camomile') AppCache
          tar -cvf AppCache.tar AppCache
          sudo rm -rf ~/.esy
          sudo rm -rf _release/Onivim2.AppDir
          
      - name: Build appimage
        run: |
          sudo tar -xf AppDir.tar
          #sudo chmod -R a+rw _release/Onivim2.AppDir
          wget -O appimagetool https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod a+x appimagetool
          ARCH=x86_64 ./appimagetool _release/Onivim2.AppDir
          sudo rm -rf _release/Onivim2.AppDir
          
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: nightly
          prerelease: true
          files: |
            AppDir.tar
            AppCache.tar
            Onivim2-x86_64.AppImage
