name: CI-windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:         
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: stable
          
      - uses: cygwin/cygwin-install-action@master
        with:
           packages: cmake
                                        
      - name: Esy setup
        run: |
          npm install -g esy@latest
          npm install -g windows-build-tools@4.0.0
          npm install -g node-gyp
          node-gyp install 14.15.4
          node install-node-deps.js
          esy install
          esy bootstrap
          esy build --verbosity=debug
          ./scripts/windows/publish.ps1
          tar -cvf AppDir.tar _publish
        shell: C:\cygwin\bin\bash.exe --noprofile --norc -o igncr -eo pipefail '{0}'
          
      - uses: actions/upload-artifact@v3
        with: 
          name: AppDirWindows
          path: AppDir.tar
                   
