name: CI-windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:         
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
                                        
      - name: Esy setup
        run: |
          npm install -g esy@latest
          npm install -g windows-build-tools@4.0.0
          npm install -g node-gyp
          node-gyp install 14.15.4
          node install-node-deps.js
          esy install
          esy bootstrap
          esy build --verbosity=debug
          esy run -f --checkhealth
          esy '@release' install
          esy '@release' run -f --checkhealth
          esy '@release' run --help
          esy '@release' create
          ls -al || echo "chau"
          find -H . || echo "hola"
          #cd _esy || echo "no _esy"
          #ls -al
          #cd oni2 || echo "no oni2"
          #ls -al
          ./scripts/windows/publish.ps1
          tar -cvf AppDir.tar _publish
          
      - uses: actions/upload-artifact@v3
        with: 
          name: AppDirWindows
          path: AppDir.tar
                   
